core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('userauth.urls')),
    # path('auth/', include('userauth.urls')),
    path('staff/', include('staff_teachers.urls')),
    path('student/', include('student.urls')),
    path('consolata/', include('consolata_admin.urls')),
    path('', include('home.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
    path('', views.student_list, name='student-list'),
    path('online-application/', views.online_application, name='online-application'),
    path('submit-online-app/', views.submit_online_application,name='submit-online-app'),
    path('results/', views.student_result,name='results'),
    path('timetable/', views.fetch_timetable, name='timetable'),
    path('generate-result-pdf/', views.generate_results_pdf, name='generate-result-pdf')
]

student/models.py
from django.db import models
from django.utils.timezone import now
from userauth.models import CustomUser


def get_year_choices():
    current_year = now().year
    return [(year, year) for year in range(2000, current_year + 1)]

MONTH_CHOICES = [
    ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'),
    ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'),
    ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')
]

TYPE_OF_SPONSOR_CHOICES = [
    ('Self', 'Self'),
    ('Congregation', 'Congregation')
]

LANGUAGE_CHOICES = [
    ('English', 'English'),
    ('French', 'French'),
    ('Spanish', 'Spanish'),
    ('Arabic', 'Arabic'),
    ('Chinese', 'Chinese'),
    ('Russian', 'Russian'),
    ('German', 'German'),
    ('Portuguese', 'Portuguese'),
    ('Hindi', 'Hindi'),
    ('Japanese', 'Japanese'),
    ('Italian', 'Italian'),
    ('Kiswahili', 'Kiswahili'),
    ('Kenyan Sign Language', 'Kenyan Sign Language'),
    ('Korean', 'Korean'),
    ('Turkish', 'Turkish'),
    ('Bengali', 'Bengali'),
    ('Persian', 'Persian'),
    ('Punjabi', 'Punjabi'),
    ('Urdu', 'Urdu'),
    ('Indonesian', 'Indonesian'),
    ('Malay', 'Malay'),
    ('Tamil', 'Tamil'),
    ('Thai', 'Thai'),
    ('Dutch', 'Dutch'),
    ('Polish', 'Polish'),
    ('Romanian', 'Romanian'),
    ('Vietnamese', 'Vietnamese'),
    ('Ukrainian', 'Ukrainian'),
    ('Greek', 'Greek'),
    ('Hebrew', 'Hebrew'),
    ('Amharic', 'Amharic'),
]

TYPE_OF_COURSE_CHOICES = [
    ('Normal', 'Normal'),
    ('Special', 'Special'),
    ('Evening & Weekend', 'Evening & Weekend'),
    ('Onsite', 'Onsite')
] 

DURATION_CHOICES = [
    ('1 Months', '1 Months'),
    ('2 Months', '2 Months'),
    ('3 Months', '3 Months'),
    ('4 Months', '4 Months')
]

MODALITY_OF_STUDY_CHOICES = [
    ('On Campus Study', 'On Campus Study'),
    ('Online Study', 'Online Study'),
    ('Both', 'Both')
]

OTHER_COURSES_CHOICES = [
    ('None', 'None'),
    ('Computer Packages', 'Computer Packages'),
    ('ICT Basic Training', 'ICT Basic Training'),
    ('English', 'English'),
    ('TOEFL', 'TOEFL'),
    ('IELTS', 'IELTS'),
    ('PITMAN', 'PITMAN'),
    ('ITALIAN', 'ITALIAN'),
    ('CIL', 'CIL'),
    ('FRENCH', 'FRENCH'),
    ('DELF', 'DELF'),
    ('DALF', 'DALF'),
]

GENDER_CHOICES = [
    ('Male', 'Male'),
    ('Female', 'Female')
]

MARITAL_STATUS_CHOICES = [
    ('Single', 'Single'),
    ('Married', 'Married'),
    ('Priest', 'Priest'),
    ('Deacon', 'Deacon'),
    ('Sister', 'Sister'),
    ('Brother', 'Brother'),
    ('Seminarian', 'Seminarian')
]

REGISTRATION_STATUS_CHOICES = [
    ('Full Time', 'Full Time'),
    ('Auditing', 'Auditing'),
    ('Weekend', 'Weekend'),
    ('Part-Time', 'Part-Time'),
    ('Evening Study', 'Evening Study'),
    ('Distance Learning', 'Distance Learning')
]

SCHOOL_CHOICES = [
    ('School Of Philosophy', 'School Of Philosophy'),
    ('School Of Theology', 'School Of Theology'),
    ('School Of Counselling Psychology', 'School Of Counselling Psychology'),

]

SCHOOL_OF_PHILOSOPHY = [
    ('Baccalaureate In Philosophy', 'Baccalaureate In Philosophy'),
    ('Bachelor Of Philosophy', 'Bachelor Of Philosophy'),
    ('Diploma In Philosophy', 'Diploma In Philosophy'),
    ('Certificate In Philosophy', 'Certificate In Philosophy'),
    ('No Award', 'No Award'),
]

SCHOOL_OF_THEOLOGY = [
    ('Baccalaureate In Theology (STB)', 'Baccalaureate In Theology (STB)'),
    ('Bachelor Of Theology (BATh)', 'Bachelor Of Theology (BATh)'),
    ('Diploma In Theology', 'Diploma In Theology'),
    ('Diploma In Religious Studies', 'Diploma In Religious Studies'),
    ('Certificate In Theology', 'Certificate In Theology'),
    ('Certificate In Religious Studies', 'Certificate In Religious Studies'),
    ('No Award', 'No Award'),
]

SCHOOL_OF_COUNSELLING_PSYCHOLOGY =[
    ('Bachelor In Counselling Psychology', 'Bachelor In Counselling Psychology'),
    ('Diploma In Counselling Psychology', 'Diploma In Counselling Psychology'),
    ('Certificate In Counselling Psychology', 'Certificate In Counselling Psychology'),
    ('No Award', 'No Award')
]

PROGRAM_DURATION = [
    ('1 Years', '1 Year'),
    ('2 Years', '2 Years'),
    ('3 Years', '3 Years'),
    ('4 Years', '4 Years')
]

YES_NO_CHOICES =[
    ('Yes','Yes'),
    ('No', 'No')
]

RECOMMENDATION_CHOICES = [
    ('Congregation', 'Congregation'),
    ('Diocese', 'Diocese'),
    ('Organisation','Organisation')
]


class TblStudentsAdmissions(models.Model):
    studentid = models.AutoField(db_column='studentID', primary_key=True)  # Field name made lowercase.
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    sir_name = models.CharField(max_length=100, null=True, blank=True)
    other_names = models.CharField(max_length=100, null=True, blank=True)
    birth_place = models.CharField(max_length=100, null=True, blank=True)
    diocese = models.CharField(max_length=100, null=True, blank=True)
    congregation = models.CharField(max_length=100, null=True, blank=True)
    permanent_adress = models.CharField(max_length=100, null=True, blank=True)
    next_of_kin = models.CharField(max_length=100, null=True, blank=True)
    next_of_kin_address = models.CharField(max_length=100, null=True, blank=True)
    next_of_kin_email = models.CharField(max_length=100, null=True, blank=True)
    next_of_kin_phone = models.CharField(max_length=100, null=True, blank=True)
    gender = models.CharField(max_length=20, choices=GENDER_CHOICES,null=True, blank=True)
    image = models.FileField(upload_to='consolata_admin/student', null=True, blank=True)
    nationality = models.CharField(max_length=20, null=True, blank=True)
    date_of_birth = models.DateField()
    id_passport = models.CharField(max_length=50, null=True, blank=True)
    contact = models.CharField(max_length=100, null=True, blank=True)
    email = models.CharField(max_length=100, null=True, blank=True)
    occupation = models.CharField(max_length=50, null=True, blank=True)
    address = models.CharField(max_length=50, null=True, blank=True)
    admission_year = models.CharField(max_length=20, choices=get_year_choices(), default=now().year)
    month = models.CharField(max_length=20, choices=MONTH_CHOICES)
    billing_self = models.CharField(max_length=100, null=True, blank=True)
    organization = models.CharField(max_length=100, null=True, blank=True)
    responsible = models.CharField(max_length=100, null=True, blank=True)
    telephone = models.CharField(max_length=100, null=True, blank=True)
    language_spoken = models.CharField(max_length=100, null=True, blank=True)
    language_to_learn = models.CharField(max_length=100, choices=LANGUAGE_CHOICES)
    course_type = models.CharField(max_length=100, choices=TYPE_OF_COURSE_CHOICES)
    duration = models.CharField(max_length=20, choices=DURATION_CHOICES)
    start_date = models.DateField(blank=True, null=True)
    other_courses = models.CharField(max_length=100, choices=OTHER_COURSES_CHOICES)
    sponsor = models.CharField(max_length=254, null=True, blank=True)
    registration_number = models.IntegerField(blank=True, null=True)
    modality = models.CharField(max_length=100, choices=MODALITY_OF_STUDY_CHOICES)
    mail_status = models.CharField(max_length=20, null=True, blank=True)
    type_of_sponsorship =  models.CharField(max_length=254,choices=TYPE_OF_SPONSOR_CHOICES, null=True, blank=True)
    marital_status = models.CharField(max_length=254,choices=MARITAL_STATUS_CHOICES, null=True, blank=True)
    registration_status = models.CharField(max_length=254,choices=REGISTRATION_STATUS_CHOICES, null=True, blank=True)
    school = models.CharField(max_length=254,choices=SCHOOL_CHOICES, null=True, blank=True)
    school_of_philosophy = models.CharField(max_length=254, choices=SCHOOL_OF_PHILOSOPHY, null=True, blank=True)
    school_of_theology = models.CharField(max_length=254, choices=SCHOOL_OF_THEOLOGY,null=True, blank=True)
    school_of_counselling = models.CharField(max_length=254, choices=SCHOOL_OF_COUNSELLING_PSYCHOLOGY, blank=True, null=True)
    anticipated_program_duration = models.CharField(max_length=254, choices=PROGRAM_DURATION, null=True, blank=True) 
    ever_studied_at_ciu = models.CharField(max_length=254, choices=YES_NO_CHOICES, null=True, blank=True)
    previous_stud_id = models.CharField(max_length=100, null=True, blank=True)
    previous_ciu_school = models.CharField(max_length=100, null=True, blank=True)
    previous_from_year = models.CharField(max_length=100, null=True, blank=True)
    prev_to_year = models.CharField(max_length=100, null=True, blank=True)
    colleges_attended = models.CharField(max_length=100, null=True, blank=True)
    high_school_attended = models.CharField(max_length=100, null=True, blank=True)
    sponsor_recomendation = models.CharField(max_length=100, null=True, blank=True)
    recommending_authority = models.CharField(max_length=100, null=True, blank=True)
    recommending_congregation = models.CharField(max_length=250, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    sponsor_address = models.CharField(max_length=250, null=True, blank=True)
    sponsor_phone = models.CharField(max_length=250,null=True, blank=True)
    sponsor_email = models.CharField(max_length=250,null=True, blank=True)
    recomendation_type = models.CharField(max_length=254, choices=RECOMMENDATION_CHOICES, null=True, blank=True)
    disability = models.CharField(max_length=254, choices=YES_NO_CHOICES, null=True, blank=True)
    how_fee_will_be_paid = models.CharField(max_length=250,null=True, blank=True)
    recomendation_address = models.CharField(max_length=250, null=True, blank=True)
    recomendation_email = models.CharField(max_length=250, null=True, blank=True)
    sponsorship_community = models.CharField(max_length=250, null=True, blank=True)

student/forms.py
from django import forms
from student.models import TblStudentsAdmissions

class StudentCreationForm(forms.ModelForm):
    class Meta:
        model = TblStudentsAdmissions
        fields = [
            # 'student',  # This is the ForeignKey to CustomUser
            'studentid','first_name','last_name','gender','image', 'nationality','date_of_birth','id_passport','contact','email','occupation','address','admission_year','month','billing_self','organization','responsible',
        'telephone','language_spoken','language_to_learn','course_type','duration','start_date','other_courses','registration_number','modality','mail_status', 'marital_status','registration_status', 'school', 'school_of_philosophy','school_of_theology','school_of_counselling', 'anticipated_program_duration', 'ever_studied_at_ciu', 'recomendation_type','disability'
        ]

student/views.py
# student/views.py

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib import messages
from .models import TblStudentsAdmissions
from .forms import StudentCreationForm
from staff_teachers.models import studentsResults, Timetable
from .utils import render_to_pdf

def student_list(request):
    return HttpResponse("This is the student list page.")

def student_result(request):
    template = 'student/student_result.html'
    result = studentsResults.objects.get(reg_no=3003)
    
    context = {
        "result": result
    }

    return render(request,template, context)

def generate_results_pdf(request):
    template = 'student/student_result_pdf.html'
    result = studentsResults.objects.get(reg_no=3003)

    data = {
        'congregation': result.congregation,
        's_no': result.s_no,
        'reg_no': result.reg_no,
        'name': result.name,
        'plato_republic':result.plato_republic,
        'modern_world_history': result.modern_world_history,
        'special_ethicks': result.special_ethicks,
        'logic': result.logic,
        'emmanuel_kant': result.emmanuel_kant,
        'edith_stein': result.edith_stein,
        'philosophical_latin': result.philosophical_latin,
        'christianity_philosophy':result.christianity_philosophy,
        'ancient_thought': result.ancient_thought,
        'comprehensive_written': result.comprehensive_written,
        'comprehensive_oral': result.comprehensives_oral
    }

    pdf = render_to_pdf(template, data)
    return HttpResponse(pdf, content_type='application/pdf')




def online_application(request):
    template ='student/online-application.html'
    form = StudentCreationForm()
    context = {
        'form':form
    }
    return render(request,template, context)
    

def submit_online_application(request):
    if request.method == 'POST':
        post = request.POST
        files = request.FILES

        application = TblStudentsAdmissions.objects.create(
            sir_name = post.get('sir-name'),
            first_name = post.get('first-name'),
            other_names = post.get('other-names'),
            gender = post.get('gender'),
            date_of_birth = post.get('birth-date'),
            birth_place = post.get('place-of-birth'),
            marital_status = post.get('marital-status'),
            diocese = post.get('diocese'),
            id_passport = post.get('passport'),
            congregation = post.get('congregation'),
            contact = post.get('permanent-address'),
            email = post.get('email'),
            telephone = post.get('phone'),
            next_of_kin = post.get('next-of-kin'),
            next_of_kin_address = post.get('next-of-kin-address'),
            next_of_kin_email = post.get('next-of-kin-email'),
            next_of_kin_phone = post.get('next-of-kin-phone'),
            registration_status = post.get('registration_status'),
            school = post.get('school'),
            school_of_philosophy = post.get('philosophy-school'),
            school_of_theology = post.get('theology-school'),
            school_of_counselling = post.get('counselling-school'),
            anticipated_program_duration = post.get('program-duration'),
            ever_studied_at_ciu = post.get('ever-studied-at-ciu'),
            previous_stud_id = post.get('previous-stud-id'),
            previous_ciu_school = post.get('previous-ciu-school'),
            previous_from_year = post.get('from'),
            prev_to_year = post.get('to'),
            colleges_attended = post.get('colleges-attended'),
            high_school_attended = post.get('high-school-attended'),
            recommending_authority = post.get('recommending-authority'),
            recommending_congregation = post.get('recommending-congregation'),
            sponsor_phone = post.get('sponsorship-phone'),
            sponsor_email = post.get('sponsor-email'),
            how_fee_will_be_paid = post.get('how-fee-will-be-paid'),
            sponsor = post.get('sponsor'),
            sponsor_recomendation = post.get('recomendation-sponsor'),
            recomendation_address = post.get('recomendation-address'),
            recomendation_phone = post.get('recomendation-phone'),
            recomendation_email = post.get('recomendation-email'),
            sponsorship_community = post.get('sponsorship-community'),
            how_you_knew_consolata = post.get('how-you-knew-consolata'),
            disability = post.get('disability'),
            disability_nature = post.get('disability-nature'),
            confirm_information = post.get('confirm-information'),
            non_refundable_fee = files.get('non-refundable-fee'),  # file field
            copy_of_id = files.get('copy-of-id'),                   # file field
            passport_photo = files.get('passport-photo'),           # file field
            coppy_of_all_degrees = files.get('coppy-of-degrees'),   # file field
            coppy_of_qualifications = files.get('coppy-of-qualifications'),  # file field
            coppy_of_transcripts = files.get('coppy-of-transcripts'),  # file field 
            copies_of_diplomas = files.get('copies-of-diplomas'),   # file field
            nationality = post.get('country')
        )

        messages.success(request, "Your online application was submitted successfully")
        return redirect('userauth:profile')

def fetch_timetable(request):
    template = 'student/student_timetable.html'
    timetables = Timetable.objects.all()
    

    context = {
        'timetables': timetables
    }

    return render(request,template, context)


    

templates/student/student_result.html
{% extends 'home/base2.html' %}
{% load static %}


{% block extracss %}
<link rel="stylesheet" href="{% static 'assets/libs/datatables.net-bs5/css/dataTables.bootstrap5.min.css' %}">
{% endblock %}

{% block objectives %}active{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="table-responsive">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h2 class="card-title">Class Results for {{request.user.first_name}}</h2>
                        <a href="{% url 'student:generate-result-pdf' %}" type="button" class="btn btn-primary text-nowrap">Generate PDF</a>
                        
                    </div>
                    
                    <table id="biannual_appraisals" class="table table-striped table-bordered display text-nowrap">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Congregation</th>
                                <th>S/No</th> 
                                <th>Reg.No</th>
                                <th>Student Name</th>
                                <th>Plato Republic</th>
                                <th>Modern World History</th>
                                <th>Special Ethics</th>
                                <th>Logic</th>
                                <th>Philosophy Of Emanuel Kant</th>
                                <th>Edith Stein Phenomenology</th>
                                <th>Philosophical Latin</th>
                                <th>Christian & Philosophy</th>
                                <th>Philosophy & Know the Ancient Thought</th>
                                <th>Comprehensives Written</th>
                                <th>Comprehensives Oral</th>

                            </tr>
                        </thead>
                        <tbody>    
                            <tr>
                                <td>{{result.id}}</td>
                                <td>{{result.congregation}}</td>
                                <td>{{result.s_no}}</td>
                                <td>{{result.reg_no}}</td>
                                <td>{{result.name}}</td>
                                <td>{{result.plato_republic}}</td>
                                <td>{{result.modern_world_history}}</td>
                                <td>{{result.special_ethicks}}</td>
                                <td>{{result.logic}}</td>
                                <td>{{result.emmanuel_kant}}</td>
                                <td>{{result.edith_stein}}</td>
                                <td>{{result.philosophical_latin}}</td>
                                <td>{{result.christianity_philosophy}}</td>
                                <td>{{result.ancient_thought}}</td>
                                <td>{{result.comprehensive_written}}</td>
                                <td>{{result.comprehensives_oral}}</td>
                            </tr>
                           
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="{% static 'assets/js/vendor.min.js' %}"></script>
<script src="{% static 'assets/libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'assets/js/datatable/datatable-basic.init.js' %}"></script>
<script>
    $(document).ready(function() {
        $('#biannual_appraisals').DataTable({
            "order": [[ 1, "desc" ]]  // Order by the Period column (4th column)
        });
    });
</script>

{% endblock %}

templates/student/student_result_pdf.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Academic Transcript</title>
  <style>
    body {
      font-family: 'Times New Roman', serif;
      font-size: 12px;
      line-height: 1.4;
      margin: 40px;
    }
    h2, h3 {
     
      margin-bottom: 5px;
    }
    .centered {
        text-align: center;
    }
    .header, .footer {
      text-align: center;
      margin-top: 10px;
    }
    .info, .signatures {
      margin-top: 20px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 10px;
      font-size: 11px;
    }
    th, td {
      border: 1px solid #000;
      padding: 3px;
      text-align: left;
    }
    .semester-title {
      font-weight: bold;
      margin-top: 15px;
    }
    .average-score {
      font-style: italic;
      margin-top: 5px;
    }
    .final-details {
      margin-top: 20px;
    }
    .stamp {
      border: 1px solid #000;
      padding: 10px;
      width: 200px;
      text-align: center;
      margin-top: 20px;
    }
    .page-break {
      page-break-before: always;
    }
  </style>
</head>
<body>

    <div style="display: flex; align-items: flex-start;">

        <!-- Left column: title + logo stacked -->
        <div style="display: flex; flex-direction: column; align-items: flex-start;">
          <h3 style="margin: 0 0 2px 0;">Consolata Institute of Philosophy</h3>
          <!-- <img src="static/img/new_logo.png" alt="Logo" style="height: 80px; width: auto; display: block;" /> -->
          <!-- <div style="margin-left: 120px;"> -->
            <p style="margin: 0;">P.O. Box 49789 - 00100 GPO, Nairobi, Kenya</p>
            <p style="margin: 0;">Tel: 020-890638 | Fax: 020-892209</p>
        </div>
      
        <!-- Right column: Address + transcript info, aligned top with title -->
        
          <h2 class="centered">ACADEMIC RECORD</h2>
          <h3 class="centered">OFFICE OF THE REGISTRAR</h3>
          <p style="margin: 0;"><strong>Monday, March 11, 2024</strong></p>
          <p style="margin: 0;">Diploma in Philosophy and Religious Studies</p>
          <p style="margin: 0;">Transcript</strong></p>
        </div>
      
      </div>
      
      

  <div class="info">
    <p><strong>Name:</strong> {{name}}</p>
    <p><strong>Matriculation No:</strong>{{reg_no}} </p>
    
  </div>

  <!-- Repeat for each semester -->
  <p class="semester-title">2020-21 Semester 2</p>
  <table>
    <tr><th>Course No.</th><th>Course Description</th><th>Score</th><th>Credit</th></tr>
    <tr><td>CPH 001</td><td>Methodology I</td><td>93.00</td><td>3.00</td></tr>
    <tr><td>CPH 100</td><td>Introduction to Philosophy</td><td>96.00</td><td>6.00</td></tr>
  </table>
  <p class="average-score">Average Score: 95.00</p>

  <!-- Repeat other semesters (insert their course rows accordingly) -->

  <div class="page-break"></div>

  <div class="final-details">
    <p><strong>Accumulated Credits:</strong> 87.68</p>
    <p><strong>Overall Average:</strong> 87.68</p>
    <p><strong>Grade Obtained:</strong> Upper Second Class Honours</p>
    <p><strong>Award Date:</strong> 11-Mar-2024</p>
    <p><strong>Signed:</strong> 10-May-2024</p>
  </div>

  <div class="signatures">
    <p><strong>DEAN OF STUDIES</strong></p>
    <p><strong>REGISTRAR</strong></p>
  </div>

  <div class="stamp">
    <p>Official Stamp</p>
  </div>

  <div class="footer">
    <p><strong>NB:</strong> All averages on this Transcript are credit sensitive</p>
    <p><strong>Interpretation of Scores:</strong></p>
    <table>
      <tr><th>Achievement Level</th><th>Score</th><th>Grade</th><th>Grd Pts</th></tr>
      <tr><td>First Class Honours</td><td>70 - &lt;100</td><td>A</td><td>0.00</td></tr>
      <tr><td>Upper Second Class Honour</td><td>60 - &lt;70</td><td>B</td><td>0.00</td></tr>
      <tr><td>Lower Second Class Honour</td><td>50 - &lt;60</td><td>C</td><td>0.00</td></tr>
      <tr><td>Adequate Pass</td><td>45 - &lt;50</td><td>D</td><td>0.00</td></tr>
      <tr><td>Bare Pass</td><td>40 - &lt;45</td><td>E</td><td>0.00</td></tr>
      <tr><td>Fail</td><td>0 - &lt;40</td><td>F</td><td>0.00</td></tr>
    </table>
    <p>Accredited by the Commission of Higher Education</p>
  </div>

</body>
</html>

templates/student/student_timetable.html
{% extends 'home/base2.html' %}
{% load static %}


{% block extracss %}
<link rel="stylesheet" href="{% static 'assets/libs/datatables.net-bs5/css/dataTables.bootstrap5.min.css' %}">
{% endblock %}

{% block objectives %}active{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="table-responsive">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h5 class="card-title"> CONSOLATA INTERNATIONAL UNIVERSITY (CIU) SEMESTER I 2025-2026 TEACHING TIMETABLE</h5>
                        
                    </div>
                    <table id="biannual_appraisals" class="table table-striped table-bordered display text-nowrap">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Day</th>
                                <th>Class</th>
                                <th>Course</th>
                                <th>From</th>
                                <th>To</th>
                                <th>Lecturer</th> 
                                <th>Room</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for table in timetables %}
                            
                            <tr>
                                <td>{{table.id}}</td>
                                <td>{{table.day}}</td>
                                <td>{{table.class_no}}</td>
                                <td>{{table.courses}}</td>
                                <td>{{table.from_time}}</td>
                                <td>{{table.to_time}}</td>
                                <td>{{table.lecturer}}</td>
                                <td>{{table.room}}</td>
                                
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'assets/js/vendor.min.js' %}"></script>
<script src="{% static 'assets/libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'assets/js/datatable/datatable-basic.init.js' %}"></script>
<script>
    $(document).ready(function() {
        $('#biannual_appraisals').DataTable({
            "order": [[ 1, "desc" ]]  // Order by the Period column (4th column)
        });
    });
</script>

{% endblock %}