core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('userauth.urls')),
    # path('auth/', include('userauth.urls')),
    path('staff/', include('staff_teachers.urls')),
    path('student/', include('student.urls')),
    path('consolata/', include('consolata_admin.urls')),
    path('', include('home.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff_teachers/urls.py
from django.urls import path
from . import views

app_name = 'staff_teachers'

urlpatterns = [
    path('teachers-pay/', views.view_teachers_pay, name='teachers-pay'),
    path('admin-office/', views.admin_office, name='admin-office'),
    path('timetable/', views.create_timetable, name='timetable'),
    path('edit-table/<int:id>', views.edit_time_table, name='edit-table'),
    path('delete-table/<int:id>', views.delete_timetable_raw, name='delete-table'),
    path('fetch-sign/', views.fetch_student_class_sign, name='fetch-sign'),
    path('upload-csv/', views.upload_results_csv, name='upload-csv'),
    path('results/', views.show_exam_results, name='results')
]

templates/staff/admin_office.html
{% extends 'home/base2.html' %}
{% load static %}

<!-- {% block profile %}active{% endblock %} -->
{% block extracss %}
<link rel="stylesheet" href="{% static 'assets/libs/datatables.net-bs5/css/dataTables.bootstrap5.min.css' %}">
{% endblock %}

{% block objectives %}active{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="table-responsive">
                <div class="card-body">
                  <div class="card card-body py-3">
                    <div class="text-center">
                      <h4 class="mb-2 card-title">ADMINISTRATOR/ACCOUNTANT DASHBOARD</h4>
                      <p class="mb-0">(GENERATION OF INVOICES/VOUCHERS/RECEIPTS)</p>
                    </div>
                  </div>
                  
                </div>
                <ul class="nav nav-pills user-profile-tab justify-content-center mt-2 bg-primary-subtle rounded-2 rounded-top-0" id="pills-tab" role="tablist">
                  <li class="nav-item" role="presentation">
                    <button class="nav-link active" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="true">
                      <span class="d-none d-md-block">School Invoices</span>
                    </button>
                  </li>
                  <li class="nav-item" role="presentation">
                    <button class="nav-link" id="pills-followers-tab" data-bs-toggle="pill" data-bs-target="#pills-followers" type="button" role="tab" aria-controls="pills-followers" aria-selected="false">
                      <span class="d-none d-md-block">Client Service Provision Invoices</span>
                    </button>
                  </li>
                </ul>
                
                <!-- ✅ SINGLE tab-content container -->
                <div class="tab-content" id="pills-tabContent">
                  <!-- School Invoices -->
                  <div class="tab-pane fade show active" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab" tabindex="0">
                    <h5><center>School Invoices</center></h5>
                    <table class="table table-striped table-bordered display text-nowrap">
                      <thead>
                        <tr>
                          <th>Name</th>
                          <th>Invoice Number</th>
                          <th>Language</th>
                          <th>Month</th>
                          <th>Amount Paid</th>
                          <th>Balance</th>
                          <th>Update Payment</th>
                          <th>Payment Status</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for invoice in school_invoices %}
                        <tr>
                          <td>{{ invoice.first_name }}</td>
                          <td>{{ invoice.invoice_number }}</td>
                          <td>{{ invoice.languages }}</td>
                          <td>{{ invoice.month }}</td>
                          <td>{{ invoice.effected_payment_ksh_total }}</td>
                          <td>{{ invoice.overall_balance_ksh_total }}</td>
                          <td><button class="btn btn-outline-secondary">View</button></td>
                          <td><button class="btn btn-outline-danger">{{ invoice.payment_status }}</button></td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                
                  <!-- Client Service Provision Invoices -->
                  <div class="tab-pane fade" id="pills-followers" role="tabpanel" aria-labelledby="pills-followers-tab" tabindex="0">
                    <h5><center>Client Service Provision Invoices</center></h5>
                    <table class="table table-striped table-bordered display text-nowrap">
                      <thead>
                        <tr>
                          <th>No.</th>
                          <th>First Name</th>
                          <th>Last Name</th>
                          <th>Language From</th>
                          <th>Language To</th>
                          <th>Month</th>
                          <th>Total</th>
                          <th>Client Status</th>
                          <th>Amount</th>
                          <th>Service Status</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for slips in record_slips %}
                        <tr>
                          <td>{{ slips.invoiceid }}</td>
                          <td>{{ slips.first_name }}</td>
                          <td>{{ slips.last_name }}</td>
                          <td>{{ slips.language_from}}</td>
                          <td>{{ slips.language_to }}</td>
                          <td>{{ slips.month }}</td>
                          <td>{{ slips.grand_total_ksh }}</td>
                          <td>{{ slips.payment_status }}</td>
                          <td>{{ slips.effected_payment_amount }}</td>
                          <td>{{ slips.service_payment_status }}</td>
                          
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
                
{% endblock %}

{% block extrajs %}
<script src="{% static 'assets/js/vendor.min.js' %}"></script>
<script src="{% static 'assets/libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'assets/js/datatable/datatable-basic.init.js' %}"></script>
<script>
    $(document).ready(function() {
        $('#biannual_appraisals').DataTable({
            "order": [[ 1, "desc" ]]  // Order by the Period column (4th column)
        });
    });
</script>

{% endblock %}

templates/staff/edit_timetable.html
{% extends 'home/base2.html' %}
{% load static %}


{% block extracss %}
<link rel="stylesheet" href="{% static 'assets/libs/datatables.net-bs5/css/dataTables.bootstrap5.min.css' %}">
{% endblock %}

{% block objectives %}active{% endblock %}

{% block content %}
<form method="post" id="submitForm" action="{% url 'staff_teachers:edit-table' table.id %}"  enctype="multipart/form-data">
    {% csrf_token %}
    <div class="card shadow mb-4">
      <div class="card-body">
        <div class="mb-5">
            <center><h5 class="card-title align-items-center">Edit  Time Table</h5></center>
        </div>
        
        <div class="row">
          <div class="col-md-6">
            <div class="form-group row">
              <label for="ticketFunction" class="col-sm-4 col-form-label">Day:</label>
              <!-- <label for="relatedRecord"><strong>Location</strong></label> -->
              <div class="col-sm-8  py-2">
                <select name="day" id="day" class="form-control" required>
                  {% for choice in form.day.field.choices %}
                    <option value="{{ choice.0 }}" {% if choice.0 == form.day.value %}selected{% endif %}>
                      {{ choice.1 }}
                    </option>
                  {% endfor %}
              </select>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group row">
              <label for="ticketFunction" class="col-sm-4 col-form-label">Class:</label>
              <div class="col-sm-8  py-2">
                <input type="text" class="form-control" id="class" name="class" value={{table.class_no}}>
              </div>
            </div>
          </div>

        </div>
        <div class="row">
            <div class="col-md-6">
              <div class="form-group row">
                <label for="ticketFunction" class="col-sm-4 col-form-label">From:</label>
                <!-- <label for="relatedRecord"><strong>Location</strong></label> -->
                <div class="col-sm-8  py-2">
                  <input type="text" class="form-control" id="from_time" name="from_time" value={{table.from_time}}>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group row">
                <label for="ticketFunction" class="col-sm-4 col-form-label">To:</label>
                <div class="col-sm-8  py-2">
                  <input type="text" class="form-control" id="to_time" name="to_time" value={{table.to_time}}>
                </div>
              </div>
            </div>
  
        </div>
        <div class="row">
            <div class="col-md-6">
              <div class="form-group row">
                <label for="ticketFunction" class="col-sm-4 col-form-label">Lecturer:</label>
                <!-- <label for="relatedRecord"><strong>Location</strong></label> -->
                <div class="col-sm-8  py-2">
                  <input type="text" class="form-control" id="lecturer" name="lecturer" value={{table.lecturer}}>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group row">
                <label for="ticketFunction" class="col-sm-4 col-form-label">Course:</label>
                <div class="col-sm-8  py-2">
                  <input type="text" class="form-control" id="courses" name="courses" value={{table.courses}}>
                </div>
              </div>
            </div>
  
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group row">
              <label for="ticketFunction" class="col-sm-4 col-form-label">Room:</label>
              <!-- <label for="relatedRecord"><strong>Location</strong></label> -->
              <div class="col-sm-8  py-2">
                <input type="text" class="form-control" id="room" name="room" value={{table.room}}>
              </div>
            </div>
          </div>
        </div>
        
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <div class="submit-spinner" id="spinner"></div>
          <button type="submit" class="btn btn-primary" id="submitButton">Submit</button>
      </div>
      </div>
    </div>
                                
  </form>

<script src="{% static 'assets/js/vendor.min.js' %}"></script>
<script src="{% static 'assets/libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'assets/js/datatable/datatable-basic.init.js' %}"></script>
<script>
    $(document).ready(function() {
        $('#biannual_appraisals').DataTable({
            "order": [[ 1, "desc" ]]  // Order by the Period column (4th column)
        });
    });
</script>

{% endblock %}

templates/staff/show_results.html
{% extends 'home/base2.html' %}
{% load static %}


{% block extracss %}
<link rel="stylesheet" href="{% static 'assets/libs/datatables.net-bs5/css/dataTables.bootstrap5.min.css' %}">
{% endblock %}

{% block objectives %}active{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="table-responsive">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h2 class="card-title">Class Results</h2>
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            
                            <form method="post" enctype="multipart/form-data" action="{% url 'staff_teachers:upload-csv' %}">
                                {% csrf_token %}
                                <label for="csv_file">Upload CSV File:</label>
                                <input type="file" name="csv_file" accept=".csv" required>
                                <button type="submit">Upload</button>
                            </form>
                        </div>
                    </div>
                    
                    <table id="biannual_appraisals" class="table table-striped table-bordered display text-nowrap">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Congregation</th>
                                <th>S/No</th> 
                                <th>Reg.No</th>
                                <th>Student Name</th>
                                <th>Plato Republic</th>
                                <th>Modern World History</th>
                                <th>Special Ethics</th>
                                <th>Logic</th>
                                <th>Philosophy Of Emanuel Kant</th>
                                <th>Edith Stein Phenomenology</th>
                                <th>Philosophical Latin</th>
                                <th>Christian & Philosophy</th>
                                <th>Philosophy & Know the Ancient Thought</th>
                                <th>Comprehensives Written</th>
                                <th>Comprehensives Oral</th>

                            </tr>
                        </thead>
                        <tbody>
                            {% for result in results %}
                            
                            <tr>
                                <td>{{result.id}}</td>
                                <td>{{result.congregation}}</td>
                                <td>{{result.s_no}}</td>
                                <td>{{result.reg_no}}</td>
                                <td>{{result.name}}</td>
                                <td>{{result.plato_republic}}</td>
                                <td>{{result.modern_world_history}}</td>
                                <td>{{result.special_ethicks}}</td>
                                <td>{{result.logic}}</td>
                                <td>{{result.emmanuel_kant}}</td>
                                <td>{{result.edith_stein}}</td>
                                <td>{{result.philosophical_latin}}</td>
                                <td>{{result.christianity_philosophy}}</td>
                                <td>{{result.ancient_thought}}</td>
                                <td>{{result.comprehensive_written}}</td>
                                <td>{{result.comprehensives_oral}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="{% static 'assets/js/vendor.min.js' %}"></script>
<script src="{% static 'assets/libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'assets/js/datatable/datatable-basic.init.js' %}"></script>
<script>
    $(document).ready(function() {
        $('#biannual_appraisals').DataTable({
            "order": [[ 1, "desc" ]]  // Order by the Period column (4th column)
        });
    });
</script>

{% endblock %}

templates/staff/timetable.html
{% extends 'home/base2.html' %}
{% load static %}


{% block extracss %}
<link rel="stylesheet" href="{% static 'assets/libs/datatables.net-bs5/css/dataTables.bootstrap5.min.css' %}">
{% endblock %}

{% block objectives %}active{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="table-responsive">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h5 class="card-title"> CONSOLATA INTERNATIONAL UNIVERSITY (CIU) SEMESTER I 2025-2026 TEACHING TIMETABLE</h5>
                        <a href="" type="button" class="btn btn-primary text-nowrap" data-bs-toggle="modal" data-bs-target="#createTimetableModal">Create Timetable</a>
                    </div>
                    <table id="biannual_appraisals" class="table table-striped table-bordered display text-nowrap">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Day</th>
                                <th>Class</th>
                                <th>Course</th>
                                <th>From</th>
                                <th>To</th>
                                <th>Lecturer</th> 
                                <th>Room</th>
                                <th></th>
                                <th></th>   
                            </tr>
                        </thead>
                        <tbody>
                            {% for table in tables %}
                            
                            <tr>
                                <td>{{table.id}}</td>
                                <td>{{table.day}}</td>
                                <td>{{table.class_no}}</td>
                                <td>{{table.courses}}</td>
                                <td>{{table.from_time}}</td>
                                <td>{{table.to_time}}</td>
                                <td>{{table.lecturer}}</td>
                                <td>{{table.room}}</td>
                                <td><a href="{% url 'staff_teachers:edit-table' table.id %}" type="button" class="btn btn-outline-primary text-nowrap" >Edit</a></td>
                                <td><a href="{% url 'staff_teachers:delete-table' table.id %}" type="button" class="btn btn-outline-danger text-nowrap" >Delete</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade mt-10" id="createTimetableModal" data-backdrop="static" data-keyboard="false" style="width:100%">
    <div class="modal-dialog modal-xl" role="document">
      <div class="modal-content">
        <div class="modal-body">
          
          <form method="post" id="submitForm" action=""  enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card shadow mb-4">
              <div class="card-body">
                <div class="mb-5">
                    <center><h5 class="card-title align-items-center">Create Timetable</h5></center>
                </div>
                
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group row">
                      <label for="ticketFunction" class="col-sm-4 col-form-label">Day:</label>
                      <!-- <label for="relatedRecord"><strong>Location</strong></label> -->
                      <div class="col-sm-8  py-2">
                        <select name="day" id="day" class="form-control" required>
                          {% for choice in form.day.field.choices %}
                            <option value="{{ choice.0 }}" {% if choice.0 == form.day.value %}selected{% endif %}>
                              {{ choice.1 }}
                            </option>
                          {% endfor %}
                      </select>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group row">
                      <label for="ticketFunction" class="col-sm-4 col-form-label">Class:</label>
                      <div class="col-sm-8  py-2">
                        <input type="text" class="form-control" id="class" name="class">
                      </div>
                    </div>
                  </div>

                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group row">
                      <label for="ticketFunction" class="col-sm-4 col-form-label">From:</label>
                      <!-- <label for="relatedRecord"><strong>Location</strong></label> -->
                      <div class="col-sm-8  py-2">
                        <input type="text" class="form-control" id="from_time" name="from_time" >
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group row">
                      <label for="ticketFunction" class="col-sm-4 col-form-label">To:</label>
                      <div class="col-sm-8  py-2">
                        <input type="text" class="form-control" id="to_time" name="to_time" >
                      </div>
                    </div>
                  </div>

                </div>
                
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group row">
                      <label for="ticketFunction" class="col-sm-4 col-form-label">Course:</label>
                      <!-- <label for="relatedRecord"><strong>Location</strong></label> -->
                      <div class="col-sm-8  py-2">
                        <input type="text" class="form-control" id="courses" name="courses" >
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group row">
                      <label for="ticketFunction" class="col-sm-4 col-form-label">Lecturer:</label>
                      <!-- <label for="relatedRecord"><strong>Location</strong></label> -->
                      <div class="col-sm-8  py-2">
                        <input type="text" class="form-control" id="lecturer" name="lecturer" >
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group row">
                        <label for="ticketFunction" class="col-sm-4 col-form-label">Room:</label>
                        <!-- <label for="relatedRecord"><strong>Location</strong></label> -->
                        <div class="col-sm-8  py-2">
                          <input type="text" class="form-control" id="room" name="room" >
                        </div>
                      </div>
                    </div>
                  </div>
                  
                
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                  <div class="submit-spinner" id="spinner"></div>
                  <button type="submit" class="btn btn-primary" id="submitButton">Submit</button>
              </div>
              </div>
            </div>
                                        
          </form>
        </div>
      </div>
    </div>
</div>

<script src="{% static 'assets/js/vendor.min.js' %}"></script>
<script src="{% static 'assets/libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'assets/js/datatable/datatable-basic.init.js' %}"></script>
<script>
    $(document).ready(function() {
        $('#biannual_appraisals').DataTable({
            "order": [[ 1, "desc" ]]  // Order by the Period column (4th column)
        });
    });
</script>

{% endblock %}